databases:
  - name: postgresql_f7qf
    databaseName: postgresql_f7qf
    user: postgresql_f7qf_user
    # plan: free

services:
  - type: web
    name: gets_ready_website
    runtime: ruby
    # plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql_f7qf
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
